name: continuous-integration

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: SSH and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          # Create ~/.ssh directory if it doesn't exist
          mkdir -p ~/.ssh
          # Write SSH private key to temporary file
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          # Set correct permissions for SSH private key
          chmod 600 ~/.ssh/id_rsa
